# permissions for end users to view domainresolvers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: domainresolver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tutorial-kubebuilder
    app.kubernetes.io/part-of: tutorial-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: domainresolver-viewer-role
rules:
- apiGroups:
  - tutorial.janosmiko.com
  resources:
  - domainresolvers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tutorial.janosmiko.com
  resources:
  - domainresolvers/status
  verbs:
  - get
